In [6]:
import numpy as np
random_array = np.random.randint(10,size=(7,2))
random_array

array([[0, 9],
       [4, 7],
       [3, 0],
       [3, 2],
       [1, 1],
       [1, 8],
       [3, 5]], dtype=int32)

In [5]:
import numpy as np
arr = np.arange(0,100,3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [9]:
import numpy as np
np.random.random((3,6))

array([[0.2547013 , 0.04234068, 0.10879802, 0.16426774, 0.86716412,
        0.5369167 ],
       [0.67668351, 0.9463257 , 0.49065347, 0.70863116, 0.49874288,
        0.16881253],
       [0.1286574 , 0.20823752, 0.83285049, 0.21441463, 0.50733116,
        0.78125123]])

In [11]:
import numpy as np
np.random.seed(42)
np.random.randint(10,size= (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [14]:
array = np.random.randint(10, size =(3,7))
print(array)
np.unique(array)

[[3 7 6 8 7 4 1]
 [4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2]]


array([0, 1, 2, 3, 4, 6, 7, 8, 9], dtype=int32)

In [17]:
a4 = np.random.randint(10, size= (3,5))
ones = np.ones((3,5))
print(a4)
print(ones)

[[6 6 8 9 9]
 [2 6 0 3 3]
 [4 6 6 3 6]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
a4 + ones

array([[ 7.,  7.,  9., 10., 10.],
       [ 3.,  7.,  1.,  4.,  4.],
       [ 5.,  7.,  7.,  4.,  7.]])

In [19]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a4 + ones

array([[ 7.,  7.,  9., 10., 10.],
       [ 3.,  7.,  1.,  4.,  4.],
       [ 5.,  7.,  7.,  4.,  7.]])

In [21]:
a4 - ones

array([[ 5.,  5.,  7.,  8.,  8.],
       [ 1.,  5., -1.,  2.,  2.],
       [ 3.,  5.,  5.,  2.,  5.]])

In [22]:
a4 * ones

array([[6., 6., 8., 9., 9.],
       [2., 6., 0., 3., 3.],
       [4., 6., 6., 3., 6.]])

In [23]:
a4 * 2

array([[12, 12, 16, 18, 18],
       [ 4, 12,  0,  6,  6],
       [ 8, 12, 12,  6, 12]], dtype=int32)

In [24]:
a4 ** 2

array([[36, 36, 64, 81, 81],
       [ 4, 36,  0,  9,  9],
       [16, 36, 36,  9, 36]], dtype=int32)

In [28]:
a4 = np.random.randint(10, size= (3,5))
print(a4)
# a4 ** 2 #square
np.square(a4)

[[1 1 5 6 4]
 [0 0 2 1 4]
 [9 5 6 3 6]]


array([[ 1,  1, 25, 36, 16],
       [ 0,  0,  4,  1, 16],
       [81, 25, 36,  9, 36]], dtype=int32)

In [29]:
np.mean(a4)

np.float64(3.533333333333333)

In [30]:
np.max(a4)

np.int32(9)

In [32]:
np.min(a4)

np.int32(0)

In [33]:
np.std(a4)

np.float64(2.578543947441829)

In [34]:
a4.T

array([[1, 0, 9],
       [1, 0, 5],
       [5, 2, 6],
       [6, 1, 3],
       [4, 4, 6]], dtype=int32)

In [35]:
a4.reshape(3,5,1)

array([[[1],
        [1],
        [5],
        [6],
        [4]],

       [[0],
        [0],
        [2],
        [1],
        [4]],

       [[9],
        [5],
        [6],
        [3],
        [6]]], dtype=int32)

In [36]:
a4.T

array([[1, 0, 9],
       [1, 0, 5],
       [5, 2, 6],
       [6, 1, 3],
       [4, 4, 6]], dtype=int32)

In [37]:
mat1 = np.random.randint(10, size = (3,3))
mat2 = np.random.randint(10, size = (3,2))
print(mat1)
print(mat2)

[[7 0 5]
 [7 4 3]
 [1 5 5]]
[[0 8]
 [5 2]
 [3 3]]


In [38]:
np.dot(mat1,mat2)

array([[15, 71],
       [29, 73],
       [40, 33]], dtype=int32)

In [39]:
mat1 = np.random.randint(10, size = (3,3))
mat2 = np.random.randint(10, size = (3,3))
print(mat1)
print(mat2)

[[2 9 2]
 [2 3 6]
 [3 8 0]]
[[7 6 1]
 [7 0 8]
 [8 1 6]]


In [40]:
np.dot(mat1, mat2)

array([[93, 14, 86],
       [83, 18, 62],
       [77, 18, 67]], dtype=int32)

In [41]:
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))
print(mat3)
print(mat4)

[[9 2 6]
 [9 8 3]
 [0 1 0]
 [4 4 6]]
[[8 8 2]
 [2 2 3]
 [7 5 7]
 [0 7 3]]


In [42]:
np.dot(mat3,mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [43]:
mat5 = np.random.randint(10, size=(4, 2))
mat6 = np.random.randint(10, size=(4, 2))
print(mat5)
print(mat6)

[[0 7]
 [3 5]
 [7 3]
 [2 8]]
[[2 8]
 [1 1]
 [1 5]
 [2 8]]


In [44]:
mat5> mat6

array([[False, False],
       [ True,  True],
       [ True, False],
       [False, False]])

In [2]:
import numpy as np
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [4]:
import numpy as np
np.random.randn(3,5)

array([[-0.27303116, -0.51085055,  1.12447323,  0.6621693 ,  0.65538001],
       [ 0.60898439, -0.76794842,  0.05136919,  0.70217047,  0.20412184],
       [ 0.458471  ,  0.53009112,  0.56386707,  2.00476725, -0.47924448]])

In [18]:
mat5 = np.random.randint(10, size=(4, 2))
mat6 = np.random.randint(10, size=(4, 2))
print(mat5)
print(mat6)

[[6 1]
 [4 0]
 [5 2]
 [2 7]]
[[2 7]
 [1 3]
 [7 4]
 [8 7]]


In [6]:
mat5 > mat6

array([[False, False],
       [False,  True],
       [False, False],
       [ True, False]])

In [7]:
mat5 >= mat6

array([[False, False],
       [False,  True],
       [False, False],
       [ True, False]])

In [8]:
mat5 > 7

array([[False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [9]:
mat5 >= 7

array([[False,  True],
       [False,  True],
       [False, False],
       [ True, False]])

In [10]:
mat5 == mat6

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [11]:
import numpy as np
np.sort(mat5)

array([[1, 7],
       [0, 7],
       [0, 3],
       [4, 9]], dtype=int32)

In [12]:
import numpy as np #it tells about indexes row wise
np.argsort(mat6)

array([[0, 1],
       [0, 1],
       [1, 0],
       [0, 1]])

In [20]:
import numpy as np
np.argmax(mat6)

np.int64(6)

In [23]:
import numpy as np
np.argmin(mat6)

np.int64(2)

In [25]:
import numpy as np
array = np.random.randint(1, 10, size=(3, 7))
print(array)
np.unique(array)

[[4 1 3 7 1 8 7]
 [4 4 1 8 1 6 1]
 [7 4 4 8 9 5 3]]


array([1, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [26]:
array[0]

array([4, 1, 3, 7, 1, 8, 7], dtype=int32)

In [27]:
array[2,2]

np.int32(4)

In [28]:
import numpy as np
np.argmax(mat5, axis = 1) #every row me maximum index btana h

array([0, 0, 0, 1])

In [31]:
print(mat5)
print(mat6)

[[6 1]
 [4 0]
 [5 2]
 [2 7]]
[[2 7]
 [1 3]
 [7 4]
 [8 7]]


In [30]:
import numpy as np
np.argmax(mat5)

np.int64(7)

In [35]:
import numpy as np
np.argmin(mat6, axis = 1)

array([0, 0, 1, 1])

In [3]:
import numpy as np
mat6 = np.random.randint(10, size=(4, 2))
print(mat6)

[[9 1]
 [5 8]
 [3 2]
 [2 4]]
